const data = [
  {
    name: "Gucci Shirt",
    category: "Shirts",
    image: "http://picsum.photos/400",
    price: 20000,
    brand: "Gucci",
    rating: 4.5,
    numReviews: 9,
    countInStock: 3,
    description: "One of our best shirts",
    slug: "gucci-shirt",
  },
  {
    name: "Gucci Trouser",
    category: "Shirts",
    image: "http://picsum.photos/401",
    price: 20000,
    brand: "Gucci",
    rating: 4.5,
    numReviews: 9,
    countInStock: 3,
    description: "One of our best shirts",
    slug: "gucci-trouser",
  },
  {
    name: "Nike Shirt",
    category: "Shirts",
    image: "http://picsum.photos/430",
    price: 20000,
    brand: "Gucci",
    rating: 4.5,
    numReviews: 9,
    countInStock: 3,
    description: "One of our best shirts",
    slug: "nike-shirt",
  },
  {
    name: "Dior Shirt",
    category: "Shirts",
    image: "http://picsum.photos/404",
    price: 20000,
    brand: "Gucci",
    rating: 4.5,
    numReviews: 9,
    countInStock: 3,
    description: "One of our best shirts",
    slug: "dior-shirt",
  },
  {
    name: "Prada Shirt",
    category: "Shirts",
    image: "http://picsum.photos/407",
    price: 20000,
    brand: "Gucci",
    rating: 4.5,
    numReviews: 9,
    countInStock: 3,
    description: "One of our best shirts",
    slug: "Prada-shirt",
  },
];

export default data;
